### ISSUE TITLE
why is there a package.json export for `package.json`?

### ISSUE THREAD

**Issue by dagda1** [tsmodule/tsmodule#1]
Hi,

Apologies if this is the wrong place to ask but I wonder if it would be possible to explain why `package.json` is included in the exports?  

```json
{
  "exports": {
    ".": "./dist/index.js",
    "./*": "./dist/components/*/index.js",
    "./styles": "./dist/styles/index.css",
    "./styles/*": "./dist/styles/*/index.css",
    "./package.json": "./package.json"
  },
}
```

**Comment by ctjlewis** [comment]
So, weirdly, there are bundlers that would throw when trying to interop between ESM and CJS if package.json was not manually specified this way in conditional exports. This field is meant to prevent that from happening at all. I think the last context I saw it in was React Native with Metro as the bundler.

This will also allow for `import pkgJson from "my-package/package.json" assert { type: "json" }` out of the box when Node supports it.

See:

  - https://github.com/vercel/next.js/issues/31514
  - https://github.com/nodejs/node/issues/33460
  - https://github.com/uuidjs/uuid/issues/444
  - https://github.com/uuidjs/uuid/pull/449
  - https://github.com/ai/nanoevents/issues/44#issuecomment-602010343
  - https://github.com/jaredh159/tailwind-react-native-classnames/pull/93
  - https://github.com/ianprime0509/pitchy/pull/108
  - https://github.com/moment/luxon/pull/1239
  - https://github.com/magiclabs/magic-js/pull/273
  - https://github.com/RubenVerborgh/AsyncIterator/pull/34
