### ISSUE TITLE
"npx" uses npm instead of yarn

### ISSUE THREAD

**Issue by ar1a** [tsmodule/tsmodule#40]
https://github.com/tsmodule/tsmodule/blob/492d841f538963c669e636d6c5368968883b243f/src/commands/build/lib/emitTsDeclarations.ts#L29

when porting my  project over from tsdx to tsmodule with `tsmodule convert`, `yarn build` fails like so 
![image](https://user-images.githubusercontent.com/8436007/202424719-b31e5a56-2738-4c1d-a0c9-6533cf2c6fbc.png)

considering tsmodule **requires** the use of yarn, i would suggest simply replacing the `npx <args>`  with `yarn <args>`

**Comment by ctjlewis** [comment]
There were weird global binary reasons that this approach was taken, as in, there’s no “yarn” equivalent of the `npx` command. I will check on this later today.

**Comment by ctjlewis** [comment]
@ar1a Can you just install NPM and make sure it's available? It's just to guarantee the tsc binary is in global PATH across operating systems. 

Yarn is less reliable with that stuff, though it is great for package management generally—you'll notice in the testing it has to use `npm link -f` over `yarn link` to guarantee deterministic behavior also.

**Comment by ar1a** [comment]
> Can you just install NPM and make sure it's available? It's just to guarantee the tsc binary is in global PATH across operating systems.

install npm? it's already installed
```
PS C:\Users\aria\Code\react-supabase-fp> npm --version
9.1.2
```

install typescript globally? that would break a lot of things i think. not only are we generating types using the tsc, which means that the versions may be mismatched down the line, also using it globally would require extra steps in ci to set up.

> there’s no “yarn” equivalent

there's [this](https://www.npmjs.com/package/ynpx) maybe? could invoke it with `npx ynpx <args>`

**Comment by ctjlewis** [comment]
We'll just ensure `typescript` is available in the project and try `yarn tsc` again. Give me an hour.

**Comment by ctjlewis** [comment]
@ar1a Can you confirm that `yarn tsc` runs in that directory as expected?

**Comment by ar1a** [comment]
> @ar1a Can you confirm that `yarn tsc` runs in that directory as expected?

```
PS C:\Users\aria\Code\react-supabase-fp> yarn tsc --version
Version 4.9.3
```

```json
  "devDependencies": {
    // ...
    "typescript": "^4.9.3"
  },
```

yep!

**Comment by ctjlewis** [comment]
@ar1a This just shipped and did seem to pass without issue. Thanks for raising this, you can upgrade now, issue shouldn't persist.

Please let me know if you have any other issues and I'll fix them quickly for you.

**Comment by ar1a** [comment]
thanks lots! ill get this going soon :)
